federation_version: 2
subgraphs:
  nasa:
    routing_url: http://localhost:4001/
    schema:
      subgraph_url: http://localhost:4001/
  xkcd:
    routing_url: http://localhost:4002/
    schema:
      subgraph_url: http://localhost:4002/
  accounts:
    routing_url: http://localhost:4003/
    schema:
      subgraph_url: http://localhost:4003/