federation_version: 2
subgraphs:
  nasa:
    routing_url: https://marstronaut-nasa.herokuapp.com/
    schema:
      subgraph_url: https://marstronaut-nasa.herokuapp.com/
  xkcd:
    routing_url: https://marstronaut-xkcd.herokuapp.com/
    schema:
      subgraph_url: https://marstronaut-xkcd.herokuapp.com/
  accounts:
    routing_url: https://marstronaut-accounts.herokuapp.com/
    schema:
      subgraph_url: https://marstronaut-accounts.herokuapp.com/